### ISSUE TITLE
Overlapping columns

### ISSUE THREAD

**Issue by peteryates** [dwp/accessibility-manual#13]
This guide is great, I'm going to share it internally. One minor thing I noticed is that when the window is resized the columns on the homepage begin to overlap. Not sure if breaking over lines or switching to a single column sooner is the answer but thought I'd let you know!

![Screenshot from 2020-12-09 09-44-53](https://user-images.githubusercontent.com/128088/101616203-fd5edf00-3a06-11eb-9f53-5c08770723f2.png)

(Firefox 83.0)

**Comment by abbott567** [comment]
Testing found the issue was due to the fact the word 'Accessibility' could not break with the column width. [Fixed in commit 3b0126a](https://github.com/dwp/accessibility-manual/commit/3307b5efe4501a2d82ac330b29e6c6c4b9cf35c2)

**Comment by abbott567** [comment]
Deployed in v1.0.1
