### ISSUE TITLE
Title content should align

### ISSUE THREAD

**Issue by abbott567** [dwp/accessibility-manual#19]
Unlike in the software engineering section, the content design section it doesn't mention the page title format:
`page title - service name - gov.uk`

This is because it was assumed that the content designer would need to title the pages, and the service name, but the software engineer would have to configure the title format in the layout.

However, on reflection, it should probably be called out in both sections so it's consistent and incase it gets missed.

**Comment by htmlandbacon** [comment]
Added PR: https://github.com/dwp/accessibility-manual/pull/20

**Comment by abbott567** [comment]
Merged with Colin Oakley's suggestions
