### ISSUE TITLE
hyperlink not active on Content Designers page

### ISSUE THREAD

**Issue by wyattr-spec** [dwp/accessibility-manual#23]
hi, thanks for the creating the accessibility guide, it's excellent. On this page https://accessibility-manual.dwp.gov.uk/guidance-for-your-job-role/content-designer the hyperlink to Office for National Statistics data is not active.

**Comment by abbott567** [comment]
@wyattr-spec it is an example, it is aria-labelled to show it's inactive for screenreaders:

```html
  <a id="testlink" href="#" aria-label="Fake link to Office for National Statistics data"> Office for National Statistics data</a>
```
However, if it's confusion, we should probably look to link out to something else and make the example use a real link.

**Comment by abbott567** [comment]
Updated in v1.1.0 to use a real link.
