### ISSUE TITLE
We'd like to collaborate with you!

### ISSUE THREAD

**Issue by myriamlamontagne** [dwp/accessibility-manual#24]
Hi there,
I'm from the Digital Accessibility in Learning team from the Canada School of Public Service (a Canadian Department) specialized in creating and delivering learning products. We're currently revamping our accessibility section in our Playbook and we'd like to collaborate with you. 

Let us know if it's something possible!

Thanks,
Myriam Lamontagne
Senior Instructional Designer in Digital Accessibility
UX Division
Canada School of Public Service / Government of Canada
myriam.lamontagne@canada.ca

**Comment by abbott567** [comment]
Hi Myriam, I have sent you an email. Look forward to discussing. =)
