### ISSUE TITLE
Assitive technology testing - several improvements

### ISSUE THREAD

**Issue by mgifford** [dwp/accessibility-manual#27]
The page here:
https://accessibility-manual.dwp.gov.uk/best-practice/assistive-technology-testing

should have a title of (missing an 's):
Assistive technology testing

I think i've you'd been using tools like this that spelling error would be caught:
https://accessibility.civicactions.com/posts/how-we-scale-inclusive-website-content-with-automated-testing-and-open-source-tools

I do this myself sometimes, so noticed:
"screenreaders" should all be "screen readers"

The paragraph:
`Every page should be tested using common screenreaders. If you’re using Apple devices you can use Voiceover for free, and if you’re using Windows then you can use NVDA for free.`

Would be improved (I think), if it were:
`Every page should be tested using common screen readers. If you’re using Apple devices VoiceOver is built-in. If you’re using Windows for testing we recommend installing the open source [NVDA](https://www.nvaccess.org/) screen reader for free. NVDA has become one of the [most popular screen readers](https://webaim.org/projects/screenreadersurvey8/) and although it is less powerful than JAWS, it is better for catching many accessibility errors.`

There is still a preference for JAWS, as it is what governments are used to testing for. There are good reasons why testers should be focusing on NVDA though. 

This is mostly in /app/views/best-practice/assistive-technology-testing/partials/screenreader-testing.md

**Comment by abbott567** [comment]
Thanks @mgifford changes made. Changed all instances of screenreader to screen reader. I think I picked up the habit from Ashleigh in the [GDS Accessibility Personas](https://www.gov.uk/government/publications/understanding-disabilities-and-impairments-user-profiles) so could be worth us raising it there to get it changed also.

**Comment by abbott567** [comment]
Updated in v1.1.0
