### ISSUE TITLE
Color Contrast

### ISSUE THREAD

**Issue by mgifford** [dwp/accessibility-manual#31]
I love WebAim.  They are great. No problem with you promoting their terrific work:
  https://accessibility.civicactions.com/guide/tools#quick-tests

That said, we're promoting two other tools for color contrast because they are open source:
  https://accessibility-manual.dwp.gov.uk/tools-and-resources/manual-accessibility-testing

The other big advantage of https://contrast-ratio.com/ is that it can take more than HEX values. HSLA works well in the web & transparencies are increasingly important.

**Comment by abbott567** [comment]
Hi @mgifford I think some of those links are in the wrong order. I've tried to work it out, and I think I've deduced that the two tools are:
- contrast ratio
- contrast checker (glitch)

I've added contrast ratio to the documentation for the next release, but it looks like the glitch application doesn't load on DWP equipment, so i've held off adding that one for now until I can see if we can get it whitelisted.

**Comment by abbott567** [comment]
Closing issue. One tool was added but one tool doesn't work on DWP equipment. Appreciate this isn't really a great reason to omit it, but as it's the DWP Manual I don't want to cause confusion for DWP staff.
