### ISSUE TITLE
Course to add to https://accessibility-manual.dwp.gov.uk/tools-and-resources/free-events-and-videos

### ISSUE THREAD

**Issue by lbwf-dwilliamson** [dwp/accessibility-manual#32]
Hi

W3C provide a free accessibility training course - https://www.w3.org/WAI/fundamentals/foundations-course/ - which you might like to add to https://accessibility-manual.dwp.gov.uk/tools-and-resources/free-events-and-videos

**Comment by abbott567** [comment]
Added in v1.1.0.
