### ISSUE TITLE
incorrect link for content designer on designing screens page

### ISSUE THREAD

**Issue by AndyPorter** [dwp/accessibility-manual#38]
https://accessibility-manual.dwp.gov.uk/best-practice/designing-screens

two links (at bottom of page)
- interaction designer
- content designer

Both links go to interaction designer advice. ie. content design link is incorrect.
Looks like content designer link should be: https://accessibility-manual.dwp.gov.uk/guidance-for-your-job-role/content-designer
As i can navigate to that page by changing the Url, or find that link elsewhere on the site.

The site is great but the way.  Just used it to help a couple of colleagues out - show that the law means internal systems have to be accessible and publish an accessibility statement.
I'm telling people this is the de-facto site for Gov accessibility advice.

**Comment by abbott567** [comment]
Thanks for this Andy. Updated and will be fixed in v2.0!
