### ISSUE TITLE
Broken link on /guidance-for-your-job-role/qa-tester

### ISSUE THREAD

**Issue by ladine-cook** [dwp/accessibility-manual#42]
On https://accessibility-manual.dwp.gov.uk/guidance-for-your-job-role/qa-tester the "manual testing using tools" link under the heading "Manual accessibility testing",  goes to "Page not found". 

I assume it needs to go to https://accessibility-manual.dwp.gov.uk/tools-and-resources/manual-accessibility-testing

**Comment by abbott567** [comment]
Fixed in version 2.1.0
