### ISSUE TITLE
Link incorrect

### ISSUE THREAD

**Issue by timcooper-DWP** [dwp/accessibility-manual#51]
![link incorrect](https://user-images.githubusercontent.com/103037700/168311535-b95e9a46-1492-4449-90d7-5a6e6d5eba0d.png)

on https://accessibility-manual.dwp.gov.uk/tools-and-resources/basic-accessibility-checks/1-automated-tools-how-to-test

should go to:
https://accessibility-manual.dwp.gov.uk/best-practice/automated-testing-using-browser-plugins#axe-devtools

currently goes to:
https://accessibility-manual.dwp.gov.uk/best-practice/automated-testing-using-browser-plugins#arc-toolkit

**Comment by abbott567** [comment]
Fixed in version 2.2.5.
