### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by timcooper-DWP** [dwp/accessibility-manual#52]
location: https://accessibility-manual.dwp.gov.uk/tools-and-resources

![Screen Shot 2022-05-13 at 16 05 57](https://user-images.githubusercontent.com/103037700/168312736-0d06531c-817d-4531-846c-156cf14e7cee.png)

Broken link to "Automated testing"

**Comment by abbott567** [comment]
Hi Tim, just going through and cleaning up the issues. This was rectified a while ago, but the issue had not been updated.
