### ISSUE TITLE
Revisiting Radio button / Checkboxes reveals

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/accessibility-manual#54]
Just following on from [ARIA attributes not allowed on conditional reveals](https://accessibility-manual.dwp.gov.uk/tools-and-resources/known-accessibility-issues#aria-attributes-not-allowed-on-conditional-reveals)

This no longer seems to align with https://github.com/alphagov/govuk-design-system-backlog/issues/37#issuecomment-871527458, so I assume should be updated?

**Comment by abbott567** [comment]
Yes, good spot. I'll remove this from the manual.

**Comment by abbott567** [comment]
Amended in version 2.2.5
