### ISSUE TITLE
Tools and resources broken link

### ISSUE THREAD

**Issue by jpmckinney** [dwp/accessibility-manual#55]
1. Open https://accessibility-manual.dwp.gov.uk
2. Click "Tools and resources" (https://accessibility-manual.dwp.gov.uk/tools-and-resources)
3. Page not found

**Comment by Finnberry** [comment]
Thanks for letting me know. The Accessibility Manual was handed over to me yesterday and it looks like something went wrong. We'll try to get it fixed as soon as possible.

**Comment by abbott567** [comment]
Hi @jpmckinney there were some teething issues when handing over all of the permissions and responsibilities as today is my last day!

I've pushed a fix, everything should be back up and running now. The codebase is no longer maintained in GitHub as part of the handover process, so you won't see it in the commits unfortunately. But if you go online everything should be working again.

Thanks,
Craig

**Comment by jpmckinney** [comment]
Thank you!
