### ISSUE TITLE
Add link to guidance about riskiest assumptions in Alpha phase

### ISSUE THREAD

**Issue by sanjaypoyzer** [dwp/accessibility-manual#6]
In `/best-practice/agile-teams#alpha`, there's an opportunity to talk about risky assumptions related to access needs.

I'd suggest linking to [the relevant page in the Service Manual](https://www.gov.uk/service-manual/agile-delivery/how-the-alpha-phase-works#focus-on-testing-your-riskiest-assumptions), and also giving some examples of accessibility related assumptions, with some content about how to find and rank risky assumptions

Proposed content:

> In Alpha, you should [focus on testing your riskiest assumptions](https://www.gov.uk/service-manual/agile-delivery/how-the-alpha-phase-works#focus-on-testing-your-riskiest-assumptions). You should take that approach with accessibility too. That means you don't need to test in Alpha with every single access need, just the ones that are most risky for your service. For example, one of your assumptions could be "Users who use screen readers will be able to access the content". If your service exclusively uses design patterns which are tried and tested, that particular access need may not be risky. But if your service uses more unique interactions, it may be more risky and so this assumption would need to be tested in Alpha.
>
> Start by working out your accessibility assumptions, by working out which access needs would affect the use of your service the most. You could use [the posters made by the Home Office](https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/) as a starting point. Next, rank each one of these in terms of their risk level. Finally, test those assumptions and iterate your design until your confident that the risk level has gone down.

**Comment by abbott567** [comment]
Hi @sanjaypoyzer I think this would be a good addition. I will look to add this in the next update. I think you've also raised a good point about linking to the service manual, this should probably be done for each phase and is a bit of an oversight! Thanks

**Comment by abbott567** [comment]
Added in version 2.1.0 (apologies it took so long)
