### ISSUE TITLE
Why is this on a .com domain?

### ISSUE THREAD

**Issue by edent** [dwp/accessibility-manual#9]
I love this initiative. I think the content is great and the guidance is useful.

But...

Why is this on a .com domain? Part of the success of modern digital government is about having a single, trusted domain.  Here are my concerns:

1. How long has this .com been registered for?
1. What are the decommissioning plans?
1. Has The National Archive been involved in preserving the content?
1. How much is this costing to register and host?
1. Is there any indication that this is a genuine service?
1. What are the risks of a scammer registering `accessibility-manual.com` and trying to deceive your users?

As I say - this is brilliant work. I'm just concerned about the proliferation of domain names, and the unintended consequences that go with them.

**Comment by abbott567** [comment]
Appreciate those concerns. The .com was only ever a temporary measure so I could get it out there for feedback. The domain https://accessibility-manual.dwp.gov.uk can now be used and the .com will be 301 redirected.
